"""empty message

Revision ID: c9f9354a1d9d
Revises: 
Create Date: 2020-05-08 14:47:14.657498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f9354a1d9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days')
    op.drop_index('ix_tasks_task_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('chats')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_table('chats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('chat_id_go', sa.INTEGER(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id_go'], ['days.day'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('day', sa.DATETIME(), nullable=True),
    sa.Column('task_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('start', sa.BOOLEAN(), nullable=True),
    sa.Column('finish', sa.BOOLEAN(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('finish IN (0, 1)'),
    sa.CheckConstraint('start IN (0, 1)'),
    sa.ForeignKeyConstraint(['day'], ['days.day'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_task_id', 'tasks', ['task_id'], unique=False)
    op.create_table('days',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('day', sa.DATE(), nullable=True),
    sa.Column('start', sa.BOOLEAN(), nullable=True),
    sa.Column('finish', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('finish IN (0, 1)'),
    sa.CheckConstraint('start IN (0, 1)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
